// AUTOGENERATED, DO NOT EDIT, generated by ../generator/gen-instr-mapping.ts
export const rangeToName = [
    {
        min: 8650496,
        max: 8650752,
        name: "PUSHNAN",
    },
    {
        min: 10485760,
        max: 10551296,
        name: "ADD",
    },
    {
        min: 10551296,
        max: 10616832,
        name: "SUB",
    },
    {
        min: 10616832,
        max: 10682368,
        name: "SUBR",
    },
    {
        min: 10682368,
        max: 10747904,
        name: "NEGATE",
    },
    {
        min: 10747904,
        max: 10813440,
        name: "INC",
    },
    {
        min: 10813440,
        max: 10878976,
        name: "DEC",
    },
    {
        min: 11010048,
        max: 11075584,
        name: "MUL",
    },
    {
        min: 11403264,
        max: 11468800,
        name: "POW2",
    },
    {
        min: 11534336,
        max: 11599872,
        name: "AND",
    },
    {
        min: 11599872,
        max: 11665408,
        name: "OR",
    },
    {
        min: 11665408,
        max: 11730944,
        name: "XOR",
    },
    {
        min: 11730944,
        max: 11796480,
        name: "NOT",
    },
    {
        min: 11927552,
        max: 11927808,
        name: "FITSX",
    },
    {
        min: 11927808,
        max: 11928064,
        name: "UFITSX",
    },
    {
        min: 11928064,
        max: 11928320,
        name: "BITSIZE",
    },
    {
        min: 11928320,
        max: 11928576,
        name: "UBITSIZE",
    },
    {
        min: 11929600,
        max: 11929856,
        name: "MIN",
    },
    {
        min: 11929856,
        max: 11930112,
        name: "MAX",
    },
    {
        min: 11930112,
        max: 11930368,
        name: "MINMAX",
    },
    {
        min: 11930368,
        max: 11930624,
        name: "ABS",
    },
    {
        min: 12034048,
        max: 12034304,
        name: "QADD",
    },
    {
        min: 12034304,
        max: 12034560,
        name: "QSUB",
    },
    {
        min: 12034560,
        max: 12034816,
        name: "QSUBR",
    },
    {
        min: 12034816,
        max: 12035072,
        name: "QNEGATE",
    },
    {
        min: 12035072,
        max: 12035328,
        name: "QINC",
    },
    {
        min: 12035328,
        max: 12035584,
        name: "QDEC",
    },
    {
        min: 12036096,
        max: 12036352,
        name: "QMUL",
    },
    {
        min: 12037632,
        max: 12037888,
        name: "QPOW2",
    },
    {
        min: 12038144,
        max: 12038400,
        name: "QAND",
    },
    {
        min: 12038400,
        max: 12038656,
        name: "QOR",
    },
    {
        min: 12038656,
        max: 12038912,
        name: "QXOR",
    },
    {
        min: 12038912,
        max: 12039168,
        name: "QNOT",
    },
    {
        min: 12039680,
        max: 12039681,
        name: "QFITSX",
    },
    {
        min: 12039681,
        max: 12039682,
        name: "QUFITSX",
    },
    {
        min: 12039682,
        max: 12039683,
        name: "QBITSIZE",
    },
    {
        min: 12039683,
        max: 12039684,
        name: "QUBITSIZE",
    },
    {
        min: 12039688,
        max: 12039689,
        name: "QMIN",
    },
    {
        min: 12039689,
        max: 12039690,
        name: "QMAX",
    },
    {
        min: 12039690,
        max: 12039691,
        name: "QMINMAX",
    },
    {
        min: 12039691,
        max: 12039692,
        name: "QABS",
    },
    {
        min: 12058624,
        max: 12124160,
        name: "SGN",
    },
    {
        min: 12124160,
        max: 12189696,
        name: "LESS",
    },
    {
        min: 12189696,
        max: 12255232,
        name: "EQUAL",
    },
    {
        min: 12255232,
        max: 12320768,
        name: "LEQ",
    },
    {
        min: 12320768,
        max: 12386304,
        name: "GREATER",
    },
    {
        min: 12386304,
        max: 12451840,
        name: "NEQ",
    },
    {
        min: 12451840,
        max: 12517376,
        name: "GEQ",
    },
    {
        min: 12517376,
        max: 12582912,
        name: "CMP",
    },
    {
        min: 12845056,
        max: 12910592,
        name: "ISNAN",
    },
    {
        min: 12910592,
        max: 12976128,
        name: "CHKNAN",
    },
    {
        min: 12040192,
        max: 12040448,
        name: "QSGN",
    },
    {
        min: 12040448,
        max: 12040704,
        name: "QLESS",
    },
    {
        min: 12040704,
        max: 12040960,
        name: "QEQUAL",
    },
    {
        min: 12040960,
        max: 12041216,
        name: "QLEQ",
    },
    {
        min: 12041216,
        max: 12041472,
        name: "QGREATER",
    },
    {
        min: 12041472,
        max: 12041728,
        name: "QNEQ",
    },
    {
        min: 12041728,
        max: 12041984,
        name: "QGEQ",
    },
    {
        min: 12041984,
        max: 12042240,
        name: "QCMP",
    },
    {
        min: 13041664,
        max: 13041920,
        name: "SEMPTY",
    },
    {
        min: 13041920,
        max: 13042176,
        name: "SDEMPTY",
    },
    {
        min: 13042176,
        max: 13042432,
        name: "SREMPTY",
    },
    {
        min: 13042432,
        max: 13042688,
        name: "SDFIRST",
    },
    {
        min: 13042688,
        max: 13042944,
        name: "SDLEXCMP",
    },
    {
        min: 13042944,
        max: 13043200,
        name: "SDEQ",
    },
    {
        min: 13043712,
        max: 13043968,
        name: "SDPFX",
    },
    {
        min: 13043968,
        max: 13044224,
        name: "SDPFXREV",
    },
    {
        min: 13044224,
        max: 13044480,
        name: "SDPPFX",
    },
    {
        min: 13044480,
        max: 13044736,
        name: "SDPPFXREV",
    },
    {
        min: 13044736,
        max: 13044992,
        name: "SDSFX",
    },
    {
        min: 13044992,
        max: 13045248,
        name: "SDSFXREV",
    },
    {
        min: 13045248,
        max: 13045504,
        name: "SDPSFX",
    },
    {
        min: 13045504,
        max: 13045760,
        name: "SDPSFXREV",
    },
    {
        min: 13045760,
        max: 13046016,
        name: "SDCNTLEAD0",
    },
    {
        min: 13046016,
        max: 13046272,
        name: "SDCNTLEAD1",
    },
    {
        min: 13046272,
        max: 13046528,
        name: "SDCNTTRAIL0",
    },
    {
        min: 13046528,
        max: 13046784,
        name: "SDCNTTRAIL1",
    },
    {
        min: 13107200,
        max: 13172736,
        name: "NEWC",
    },
    {
        min: 13172736,
        max: 13238272,
        name: "ENDC",
    },
    {
        min: 13434880,
        max: 13500416,
        name: "ENDCST",
    },
    {
        min: 13570304,
        max: 13570560,
        name: "STBREF",
    },
    {
        min: 13570816,
        max: 13571072,
        name: "STB",
    },
    {
        min: 13571072,
        max: 13571328,
        name: "STREFR",
    },
    {
        min: 13571328,
        max: 13571584,
        name: "STBREFR",
    },
    {
        min: 13571584,
        max: 13571840,
        name: "STSLICER",
    },
    {
        min: 13571840,
        max: 13572096,
        name: "STBR",
    },
    {
        min: 13572096,
        max: 13572352,
        name: "STREFQ",
    },
    {
        min: 13572352,
        max: 13572608,
        name: "STBREFQ",
    },
    {
        min: 13572608,
        max: 13572864,
        name: "STSLICEQ",
    },
    {
        min: 13572864,
        max: 13573120,
        name: "STBQ",
    },
    {
        min: 13573120,
        max: 13573376,
        name: "STREFRQ",
    },
    {
        min: 13573376,
        max: 13573632,
        name: "STBREFRQ",
    },
    {
        min: 13573632,
        max: 13573888,
        name: "STSLICERQ",
    },
    {
        min: 13573888,
        max: 13574144,
        name: "STBRQ",
    },
    {
        min: 13574912,
        max: 13575168,
        name: "ENDXC",
    },
    {
        min: 13578240,
        max: 13578496,
        name: "BDEPTH",
    },
    {
        min: 13578496,
        max: 13578752,
        name: "BBITS",
    },
    {
        min: 13578752,
        max: 13579008,
        name: "BREFS",
    },
    {
        min: 13579008,
        max: 13579264,
        name: "BBITREFS",
    },
    {
        min: 13579520,
        max: 13579776,
        name: "BREMBITS",
    },
    {
        min: 13579776,
        max: 13580032,
        name: "BREMREFS",
    },
    {
        min: 13580032,
        max: 13580288,
        name: "BREMBITREFS",
    },
    {
        min: 13580800,
        max: 13581056,
        name: "BCHKREFS",
    },
    {
        min: 13581056,
        max: 13581312,
        name: "BCHKBITREFS",
    },
    {
        min: 13581824,
        max: 13582080,
        name: "BCHKREFSQ",
    },
    {
        min: 13582080,
        max: 13582336,
        name: "BCHKBITREFSQ",
    },
    {
        min: 13582336,
        max: 13582592,
        name: "STZEROES",
    },
    {
        min: 13582592,
        max: 13582848,
        name: "STONES",
    },
    {
        min: 13582848,
        max: 13583104,
        name: "STSAME",
    },
    {
        min: 13631488,
        max: 13697024,
        name: "CTOS",
    },
    {
        min: 13697024,
        max: 13762560,
        name: "ENDS",
    },
    {
        min: 13893632,
        max: 13959168,
        name: "LDREF",
    },
    {
        min: 13959168,
        max: 14024704,
        name: "LDREFRTOS",
    },
    {
        min: 14098432,
        max: 14098688,
        name: "SDCUTFIRST",
    },
    {
        min: 14098688,
        max: 14098944,
        name: "SDSKIPFIRST",
    },
    {
        min: 14098944,
        max: 14099200,
        name: "SDCUTLAST",
    },
    {
        min: 14099200,
        max: 14099456,
        name: "SDSKIPLAST",
    },
    {
        min: 14099456,
        max: 14099712,
        name: "SDSUBSTR",
    },
    {
        min: 14102528,
        max: 14102784,
        name: "SCUTFIRST",
    },
    {
        min: 14102784,
        max: 14103040,
        name: "SSKIPFIRST",
    },
    {
        min: 14103040,
        max: 14103296,
        name: "SCUTLAST",
    },
    {
        min: 14103296,
        max: 14103552,
        name: "SSKIPLAST",
    },
    {
        min: 14103552,
        max: 14103808,
        name: "SUBSLICE",
    },
    {
        min: 14104064,
        max: 14104320,
        name: "SPLIT",
    },
    {
        min: 14104320,
        max: 14104576,
        name: "SPLITQ",
    },
    {
        min: 14104832,
        max: 14105088,
        name: "XCTOS",
    },
    {
        min: 14105088,
        max: 14105344,
        name: "XLOAD",
    },
    {
        min: 14105344,
        max: 14105600,
        name: "XLOADQ",
    },
    {
        min: 14106880,
        max: 14107136,
        name: "SCHKBITS",
    },
    {
        min: 14107136,
        max: 14107392,
        name: "SCHKREFS",
    },
    {
        min: 14107392,
        max: 14107648,
        name: "SCHKBITREFS",
    },
    {
        min: 14107904,
        max: 14108160,
        name: "SCHKBITSQ",
    },
    {
        min: 14108160,
        max: 14108416,
        name: "SCHKREFSQ",
    },
    {
        min: 14108416,
        max: 14108672,
        name: "SCHKBITREFSQ",
    },
    {
        min: 14108672,
        max: 14108928,
        name: "PLDREFVAR",
    },
    {
        min: 14108928,
        max: 14109184,
        name: "SBITS",
    },
    {
        min: 14109184,
        max: 14109440,
        name: "SREFS",
    },
    {
        min: 14109440,
        max: 14109696,
        name: "SBITREFS",
    },
    {
        min: 14114816,
        max: 14115072,
        name: "LDZEROES",
    },
    {
        min: 14115072,
        max: 14115328,
        name: "LDONES",
    },
    {
        min: 14115328,
        max: 14115584,
        name: "LDSAME",
    },
    {
        min: 14115840,
        max: 14116096,
        name: "SDEPTH",
    },
    {
        min: 14116096,
        max: 14116352,
        name: "CDEPTH",
    },
    {
        min: 14116352,
        max: 14116608,
        name: "CLEVEL",
    },
    {
        min: 14116608,
        max: 14116864,
        name: "CLEVELMASK",
    },
    {
        min: 14118912,
        max: 14119168,
        name: "CHASHIX",
    },
    {
        min: 14119168,
        max: 14119424,
        name: "CDEPTHIX",
    },
    {
        min: 14155776,
        max: 14221312,
        name: "EXECUTE",
    },
    {
        min: 14221312,
        max: 14286848,
        name: "JMPX",
    },
    {
        min: 14364672,
        max: 14364928,
        name: "RET",
    },
    {
        min: 14364928,
        max: 14365184,
        name: "RETALT",
    },
    {
        min: 14365184,
        max: 14365440,
        name: "RETBOOL",
    },
    {
        min: 14365696,
        max: 14365952,
        name: "CALLCC",
    },
    {
        min: 14365952,
        max: 14366208,
        name: "JMPXDATA",
    },
    {
        min: 14366720,
        max: 14366976,
        name: "CALLXVARARGS",
    },
    {
        min: 14366976,
        max: 14367232,
        name: "RETVARARGS",
    },
    {
        min: 14367232,
        max: 14367488,
        name: "JMPXVARARGS",
    },
    {
        min: 14367488,
        max: 14367744,
        name: "CALLCCVARARGS",
    },
    {
        min: 14368512,
        max: 14368768,
        name: "RETDATA",
    },
    {
        min: 14372864,
        max: 14373120,
        name: "RUNVMX",
    },
    {
        min: 14417920,
        max: 14483456,
        name: "IFRET",
    },
    {
        min: 14483456,
        max: 14548992,
        name: "IFNOTRET",
    },
    {
        min: 14548992,
        max: 14614528,
        name: "IF",
    },
    {
        min: 14614528,
        max: 14680064,
        name: "IFNOT",
    },
    {
        min: 14680064,
        max: 14745600,
        name: "IFJMP",
    },
    {
        min: 14745600,
        max: 14811136,
        name: "IFNOTJMP",
    },
    {
        min: 14811136,
        max: 14876672,
        name: "IFELSE",
    },
    {
        min: 14877696,
        max: 14877952,
        name: "CONDSEL",
    },
    {
        min: 14877952,
        max: 14878208,
        name: "CONDSELCHK",
    },
    {
        min: 14878720,
        max: 14878976,
        name: "IFRETALT",
    },
    {
        min: 14878976,
        max: 14879232,
        name: "IFNOTRETALT",
    },
    {
        min: 14942208,
        max: 15007744,
        name: "REPEAT",
    },
    {
        min: 15007744,
        max: 15073280,
        name: "REPEATEND",
    },
    {
        min: 15073280,
        max: 15138816,
        name: "UNTIL",
    },
    {
        min: 15138816,
        max: 15204352,
        name: "UNTILEND",
    },
    {
        min: 15204352,
        max: 15269888,
        name: "WHILE",
    },
    {
        min: 15269888,
        max: 15335424,
        name: "WHILEEND",
    },
    {
        min: 15335424,
        max: 15400960,
        name: "AGAIN",
    },
    {
        min: 15400960,
        max: 15466496,
        name: "AGAINEND",
    },
    {
        min: 14881792,
        max: 14882048,
        name: "REPEATBRK",
    },
    {
        min: 14882048,
        max: 14882304,
        name: "REPEATENDBRK",
    },
    {
        min: 14882304,
        max: 14882560,
        name: "UNTILBRK",
    },
    {
        min: 14882560,
        max: 14882816,
        name: "UNTILENDBRK",
    },
    {
        min: 14882816,
        max: 14883072,
        name: "WHILEBRK",
    },
    {
        min: 14883072,
        max: 14883328,
        name: "WHILEENDBRK",
    },
    {
        min: 14883328,
        max: 14883584,
        name: "AGAINBRK",
    },
    {
        min: 14883584,
        max: 14883840,
        name: "AGAINENDBRK",
    },
    {
        min: 15536128,
        max: 15536384,
        name: "RETURNVARARGS",
    },
    {
        min: 15536384,
        max: 15536640,
        name: "SETCONTVARARGS",
    },
    {
        min: 15536640,
        max: 15536896,
        name: "SETNUMVARARGS",
    },
    {
        min: 15539712,
        max: 15539968,
        name: "BLESS",
    },
    {
        min: 15539968,
        max: 15540224,
        name: "BLESSVARARGS",
    },
    {
        min: 15589376,
        max: 15589632,
        name: "PUSHCTRX",
    },
    {
        min: 15589632,
        max: 15589888,
        name: "POPCTRX",
    },
    {
        min: 15589888,
        max: 15590144,
        name: "SETCONTCTRX",
    },
    {
        min: 15590400,
        max: 15590656,
        name: "SETCONTCTRMANYX",
    },
    {
        min: 15593472,
        max: 15593728,
        name: "BOOLAND",
    },
    {
        min: 15593728,
        max: 15593984,
        name: "BOOLOR",
    },
    {
        min: 15593984,
        max: 15594240,
        name: "COMPOSBOTH",
    },
    {
        min: 15594240,
        max: 15594496,
        name: "ATEXIT",
    },
    {
        min: 15594496,
        max: 15594752,
        name: "ATEXITALT",
    },
    {
        min: 15594752,
        max: 15595008,
        name: "SETEXITALT",
    },
    {
        min: 15595008,
        max: 15595264,
        name: "THENRET",
    },
    {
        min: 15595264,
        max: 15595520,
        name: "THENRETALT",
    },
    {
        min: 15595520,
        max: 15595776,
        name: "INVERT",
    },
    {
        min: 15595776,
        max: 15596032,
        name: "BOOLEVAL",
    },
    {
        min: 15596032,
        max: 15596288,
        name: "SAMEALT",
    },
    {
        min: 15596288,
        max: 15596544,
        name: "SAMEALTSAVE",
    },
    {
        min: 15924992,
        max: 15925248,
        name: "TRY",
    },
    {
        min: 15990784,
        max: 15991040,
        name: "STDICT",
    },
    {
        min: 15991040,
        max: 15991296,
        name: "SKIPDICT",
    },
    {
        min: 15991296,
        max: 15991552,
        name: "LDDICTS",
    },
    {
        min: 15991552,
        max: 15991808,
        name: "PLDDICTS",
    },
    {
        min: 15991808,
        max: 15992064,
        name: "LDDICT",
    },
    {
        min: 15992064,
        max: 15992320,
        name: "PLDDICT",
    },
    {
        min: 15992320,
        max: 15992576,
        name: "LDDICTQ",
    },
    {
        min: 15992576,
        max: 15992832,
        name: "PLDDICTQ",
    },
    {
        min: 16019456,
        max: 16019712,
        name: "PFXDICTSET",
    },
    {
        min: 16019712,
        max: 16019968,
        name: "PFXDICTREPLACE",
    },
    {
        min: 16019968,
        max: 16020224,
        name: "PFXDICTADD",
    },
    {
        min: 16020224,
        max: 16020480,
        name: "PFXDICTDEL",
    },
    {
        min: 16033792,
        max: 16034048,
        name: "PFXDICTGETQ",
    },
    {
        min: 16034048,
        max: 16034304,
        name: "PFXDICTGET",
    },
    {
        min: 16034304,
        max: 16034560,
        name: "PFXDICTGETJMP",
    },
    {
        min: 16034560,
        max: 16034816,
        name: "PFXDICTGETEXEC",
    },
    {
        min: 0,
        max: 65536,
        name: "NOP",
    },
    {
        min: 65536,
        max: 131072,
        name: "SWAP",
    },
    {
        min: 2097152,
        max: 2162688,
        name: "DUP",
    },
    {
        min: 2162688,
        max: 2228224,
        name: "OVER",
    },
    {
        min: 3145728,
        max: 3211264,
        name: "DROP",
    },
    {
        min: 3211264,
        max: 3276800,
        name: "NIP",
    },
    {
        min: 5767168,
        max: 5832704,
        name: "ROT",
    },
    {
        min: 5832704,
        max: 5898240,
        name: "ROTREV",
    },
    {
        min: 6291456,
        max: 6356992,
        name: "PICK",
    },
    {
        min: 6356992,
        max: 6422528,
        name: "ROLL",
    },
    {
        min: 6422528,
        max: 6488064,
        name: "ROLLREV",
    },
    {
        min: 6488064,
        max: 6553600,
        name: "BLKSWX",
    },
    {
        min: 6553600,
        max: 6619136,
        name: "REVX",
    },
    {
        min: 6619136,
        max: 6684672,
        name: "DROPX",
    },
    {
        min: 6684672,
        max: 6750208,
        name: "TUCK",
    },
    {
        min: 6750208,
        max: 6815744,
        name: "XCHGX",
    },
    {
        min: 6815744,
        max: 6881280,
        name: "DEPTH",
    },
    {
        min: 6881280,
        max: 6946816,
        name: "CHKDEPTH",
    },
    {
        min: 6946816,
        max: 7012352,
        name: "ONLYTOPX",
    },
    {
        min: 7012352,
        max: 7077888,
        name: "ONLYX",
    },
    {
        min: 16252928,
        max: 16253184,
        name: "ACCEPT",
    },
    {
        min: 16253184,
        max: 16253440,
        name: "SETGASLIMIT",
    },
    {
        min: 16254720,
        max: 16254976,
        name: "GASCONSUMED",
    },
    {
        min: 16256768,
        max: 16257024,
        name: "COMMIT",
    },
    {
        min: 16261888,
        max: 16262144,
        name: "NOW",
    },
    {
        min: 16262144,
        max: 16262400,
        name: "BLOCKLT",
    },
    {
        min: 16262400,
        max: 16262656,
        name: "LTIME",
    },
    {
        min: 16262656,
        max: 16262912,
        name: "RANDSEED",
    },
    {
        min: 16262912,
        max: 16263168,
        name: "BALANCE",
    },
    {
        min: 16263168,
        max: 16263424,
        name: "MYADDR",
    },
    {
        min: 16263424,
        max: 16263680,
        name: "CONFIGROOT",
    },
    {
        min: 16263680,
        max: 16263936,
        name: "MYCODE",
    },
    {
        min: 16263936,
        max: 16264192,
        name: "INCOMINGVALUE",
    },
    {
        min: 16264192,
        max: 16264448,
        name: "STORAGEFEES",
    },
    {
        min: 16264448,
        max: 16264704,
        name: "PREVBLOCKSINFOTUPLE",
    },
    {
        min: 16264704,
        max: 16264960,
        name: "UNPACKEDCONFIGTUPLE",
    },
    {
        min: 16264960,
        max: 16265216,
        name: "DUEPAYMENT",
    },
    {
        min: 16265216,
        max: 16265472,
        name: "CONFIGDICT",
    },
    {
        min: 16265728,
        max: 16265984,
        name: "CONFIGPARAM",
    },
    {
        min: 16265984,
        max: 16266240,
        name: "CONFIGOPTPARAM",
    },
    {
        min: 16266240,
        max: 16266241,
        name: "PREVMCBLOCKS",
    },
    {
        min: 16266241,
        max: 16266242,
        name: "PREVKEYBLOCK",
    },
    {
        min: 16266242,
        max: 16266243,
        name: "PREVMCBLOCKS_100",
    },
    {
        min: 16266496,
        max: 16266752,
        name: "GLOBALID",
    },
    {
        min: 16266752,
        max: 16267008,
        name: "GETGASFEE",
    },
    {
        min: 16267008,
        max: 16267264,
        name: "GETSTORAGEFEE",
    },
    {
        min: 16267264,
        max: 16267520,
        name: "GETFORWARDFEE",
    },
    {
        min: 16267520,
        max: 16267776,
        name: "GETPRECOMPILEDGAS",
    },
    {
        min: 16267776,
        max: 16268032,
        name: "GETORIGINALFWDFEE",
    },
    {
        min: 16268032,
        max: 16268288,
        name: "GETGASFEESIMPLE",
    },
    {
        min: 16268288,
        max: 16268544,
        name: "GETFORWARDFEESIMPLE",
    },
    {
        min: 16269312,
        max: 16269568,
        name: "GETGLOBVAR",
    },
    {
        min: 16277504,
        max: 16277760,
        name: "SETGLOBVAR",
    },
    {
        min: 16257024,
        max: 16257280,
        name: "RANDU256",
    },
    {
        min: 16257280,
        max: 16257536,
        name: "RAND",
    },
    {
        min: 16258048,
        max: 16258304,
        name: "SETRAND",
    },
    {
        min: 16258304,
        max: 16258560,
        name: "ADDRAND",
    },
    {
        min: 16318464,
        max: 16318720,
        name: "HASHCU",
    },
    {
        min: 16318720,
        max: 16318976,
        name: "HASHSU",
    },
    {
        min: 16318976,
        max: 16319232,
        name: "SHA256U",
    },
    {
        min: 16322560,
        max: 16322816,
        name: "CHKSIGNU",
    },
    {
        min: 16322816,
        max: 16323072,
        name: "CHKSIGNS",
    },
    {
        min: 16323072,
        max: 16323328,
        name: "ECRECOVER",
    },
    {
        min: 16323328,
        max: 16323584,
        name: "SECP256K1_XONLY_PUBKEY_TWEAK_ADD",
    },
    {
        min: 16323584,
        max: 16323840,
        name: "P256_CHKSIGNU",
    },
    {
        min: 16323840,
        max: 16324096,
        name: "P256_CHKSIGNS",
    },
    {
        min: 16326656,
        max: 16326912,
        name: "RIST255_FROMHASH",
    },
    {
        min: 16326912,
        max: 16327168,
        name: "RIST255_VALIDATE",
    },
    {
        min: 16327168,
        max: 16327424,
        name: "RIST255_ADD",
    },
    {
        min: 16327424,
        max: 16327680,
        name: "RIST255_SUB",
    },
    {
        min: 16327680,
        max: 16327936,
        name: "RIST255_MUL",
    },
    {
        min: 16327936,
        max: 16328192,
        name: "RIST255_MULBASE",
    },
    {
        min: 16328192,
        max: 16328448,
        name: "RIST255_PUSHL",
    },
    {
        min: 12056865,
        max: 12056866,
        name: "RIST255_QVALIDATE",
    },
    {
        min: 12056866,
        max: 12056867,
        name: "RIST255_QADD",
    },
    {
        min: 12056867,
        max: 12056868,
        name: "RIST255_QSUB",
    },
    {
        min: 12056868,
        max: 12056869,
        name: "RIST255_QMUL",
    },
    {
        min: 12056869,
        max: 12056870,
        name: "RIST255_QMULBASE",
    },
    {
        min: 16330752,
        max: 16330753,
        name: "BLS_VERIFY",
    },
    {
        min: 16330753,
        max: 16330754,
        name: "BLS_AGGREGATE",
    },
    {
        min: 16330754,
        max: 16330755,
        name: "BLS_FASTAGGREGATEVERIFY",
    },
    {
        min: 16330755,
        max: 16330756,
        name: "BLS_AGGREGATEVERIFY",
    },
    {
        min: 16330768,
        max: 16330769,
        name: "BLS_G1_ADD",
    },
    {
        min: 16330769,
        max: 16330770,
        name: "BLS_G1_SUB",
    },
    {
        min: 16330770,
        max: 16330771,
        name: "BLS_G1_NEG",
    },
    {
        min: 16330771,
        max: 16330772,
        name: "BLS_G1_MUL",
    },
    {
        min: 16330772,
        max: 16330773,
        name: "BLS_G1_MULTIEXP",
    },
    {
        min: 16330773,
        max: 16330774,
        name: "BLS_G1_ZERO",
    },
    {
        min: 16330774,
        max: 16330775,
        name: "BLS_MAP_TO_G1",
    },
    {
        min: 16330775,
        max: 16330776,
        name: "BLS_G1_INGROUP",
    },
    {
        min: 16330776,
        max: 16330777,
        name: "BLS_G1_ISZERO",
    },
    {
        min: 16330784,
        max: 16330785,
        name: "BLS_G2_ADD",
    },
    {
        min: 16330785,
        max: 16330786,
        name: "BLS_G2_SUB",
    },
    {
        min: 16330786,
        max: 16330787,
        name: "BLS_G2_NEG",
    },
    {
        min: 16330787,
        max: 16330788,
        name: "BLS_G2_MUL",
    },
    {
        min: 16330788,
        max: 16330789,
        name: "BLS_G2_MULTIEXP",
    },
    {
        min: 16330789,
        max: 16330790,
        name: "BLS_G2_ZERO",
    },
    {
        min: 16330790,
        max: 16330791,
        name: "BLS_MAP_TO_G2",
    },
    {
        min: 16330791,
        max: 16330792,
        name: "BLS_G2_INGROUP",
    },
    {
        min: 16330792,
        max: 16330793,
        name: "BLS_G2_ISZERO",
    },
    {
        min: 16330800,
        max: 16330801,
        name: "BLS_PAIRING",
    },
    {
        min: 16330801,
        max: 16330802,
        name: "BLS_PUSHR",
    },
    {
        min: 16334848,
        max: 16335104,
        name: "CDATASIZEQ",
    },
    {
        min: 16335104,
        max: 16335360,
        name: "CDATASIZE",
    },
    {
        min: 16335360,
        max: 16335616,
        name: "SDATASIZEQ",
    },
    {
        min: 16335616,
        max: 16335872,
        name: "SDATASIZE",
    },
    {
        min: 16384000,
        max: 16384256,
        name: "LDGRAMS",
    },
    {
        min: 16384256,
        max: 16384512,
        name: "LDVARINT16",
    },
    {
        min: 16384512,
        max: 16384768,
        name: "STGRAMS",
    },
    {
        min: 16384768,
        max: 16385024,
        name: "STVARINT16",
    },
    {
        min: 16385024,
        max: 16385280,
        name: "LDVARUINT32",
    },
    {
        min: 16385280,
        max: 16385536,
        name: "LDVARINT32",
    },
    {
        min: 16385536,
        max: 16385792,
        name: "STVARUINT32",
    },
    {
        min: 16385792,
        max: 16386048,
        name: "STVARINT32",
    },
    {
        min: 16400384,
        max: 16400640,
        name: "LDMSGADDR",
    },
    {
        min: 16400640,
        max: 16400896,
        name: "LDMSGADDRQ",
    },
    {
        min: 16400896,
        max: 16401152,
        name: "PARSEMSGADDR",
    },
    {
        min: 16401152,
        max: 16401408,
        name: "PARSEMSGADDRQ",
    },
    {
        min: 16401408,
        max: 16401664,
        name: "REWRITESTDADDR",
    },
    {
        min: 16401664,
        max: 16401920,
        name: "REWRITESTDADDRQ",
    },
    {
        min: 16401920,
        max: 16402176,
        name: "REWRITEVARADDR",
    },
    {
        min: 16402176,
        max: 16402432,
        name: "REWRITEVARADDRQ",
    },
    {
        min: 16449536,
        max: 16449792,
        name: "SENDRAWMSG",
    },
    {
        min: 16450048,
        max: 16450304,
        name: "RAWRESERVE",
    },
    {
        min: 16450304,
        max: 16450560,
        name: "RAWRESERVEX",
    },
    {
        min: 16450560,
        max: 16450816,
        name: "SETCODE",
    },
    {
        min: 16451072,
        max: 16451328,
        name: "SETLIBCODE",
    },
    {
        min: 16451328,
        max: 16451584,
        name: "CHANGELIB",
    },
    {
        min: 16451584,
        max: 16451840,
        name: "SENDMSG",
    },
    {
        min: 7143424,
        max: 7208960,
        name: "PUSHNULL",
    },
    {
        min: 7208960,
        max: 7274496,
        name: "ISNULL",
    },
    {
        min: 7307264,
        max: 7307520,
        name: "TUPLEVAR",
    },
    {
        min: 7307520,
        max: 7307776,
        name: "INDEXVAR",
    },
    {
        min: 7307776,
        max: 7308032,
        name: "UNTUPLEVAR",
    },
    {
        min: 7308032,
        max: 7308288,
        name: "UNPACKFIRSTVAR",
    },
    {
        min: 7308288,
        max: 7308544,
        name: "EXPLODEVAR",
    },
    {
        min: 7308544,
        max: 7308800,
        name: "SETINDEXVAR",
    },
    {
        min: 7308800,
        max: 7309056,
        name: "INDEXVARQ",
    },
    {
        min: 7309056,
        max: 7309312,
        name: "SETINDEXVARQ",
    },
    {
        min: 7309312,
        max: 7309568,
        name: "TLEN",
    },
    {
        min: 7309568,
        max: 7309824,
        name: "QTLEN",
    },
    {
        min: 7309824,
        max: 7310080,
        name: "ISTUPLE",
    },
    {
        min: 7310080,
        max: 7310336,
        name: "LAST",
    },
    {
        min: 7310336,
        max: 7310592,
        name: "TPUSH",
    },
    {
        min: 7310592,
        max: 7310848,
        name: "TPOP",
    },
    {
        min: 7315456,
        max: 7315712,
        name: "NULLSWAPIF",
    },
    {
        min: 7315712,
        max: 7315968,
        name: "NULLSWAPIFNOT",
    },
    {
        min: 7315968,
        max: 7316224,
        name: "NULLROTRIF",
    },
    {
        min: 7316224,
        max: 7316480,
        name: "NULLROTRIFNOT",
    },
    {
        min: 7316480,
        max: 7316736,
        name: "NULLSWAPIF2",
    },
    {
        min: 7316736,
        max: 7316992,
        name: "NULLSWAPIFNOT2",
    },
    {
        min: 7316992,
        max: 7317248,
        name: "NULLROTRIF2",
    },
    {
        min: 7317248,
        max: 7317504,
        name: "NULLROTRIFNOT2",
    },
    {
        min: 11075584,
        max: 11075840,
        name: "ADDDIVMOD",
    },
    {
        min: 11075840,
        max: 11076096,
        name: "ADDDIVMODR",
    },
    {
        min: 11076096,
        max: 11076352,
        name: "ADDDIVMODC",
    },
    {
        min: 11076608,
        max: 11076864,
        name: "DIV",
    },
    {
        min: 11076864,
        max: 11077120,
        name: "DIVR",
    },
    {
        min: 11077120,
        max: 11077376,
        name: "DIVC",
    },
    {
        min: 11077632,
        max: 11077888,
        name: "MOD",
    },
    {
        min: 11077888,
        max: 11078144,
        name: "MODR",
    },
    {
        min: 11078144,
        max: 11078400,
        name: "MODC",
    },
    {
        min: 11078656,
        max: 11078912,
        name: "DIVMOD",
    },
    {
        min: 11078912,
        max: 11079168,
        name: "DIVMODR",
    },
    {
        min: 11079168,
        max: 11079424,
        name: "DIVMODC",
    },
    {
        min: 12036352,
        max: 12036353,
        name: "QADDDIVMOD",
    },
    {
        min: 12036353,
        max: 12036354,
        name: "QADDDIVMODR",
    },
    {
        min: 12036354,
        max: 12036355,
        name: "QADDDIVMODC",
    },
    {
        min: 12036356,
        max: 12036357,
        name: "QDIV",
    },
    {
        min: 12036357,
        max: 12036358,
        name: "QDIVR",
    },
    {
        min: 12036358,
        max: 12036359,
        name: "QDIVC",
    },
    {
        min: 12036360,
        max: 12036361,
        name: "QMOD",
    },
    {
        min: 12036361,
        max: 12036362,
        name: "QMODR",
    },
    {
        min: 12036362,
        max: 12036363,
        name: "QMODC",
    },
    {
        min: 12036364,
        max: 12036365,
        name: "QDIVMOD",
    },
    {
        min: 12036365,
        max: 12036366,
        name: "QDIVMODR",
    },
    {
        min: 12036366,
        max: 12036367,
        name: "QDIVMODC",
    },
    {
        min: 11083776,
        max: 11084032,
        name: "ADDRSHIFTMOD",
    },
    {
        min: 11084032,
        max: 11084288,
        name: "ADDRSHIFTMODR",
    },
    {
        min: 11084288,
        max: 11084544,
        name: "ADDRSHIFTMODC",
    },
    {
        min: 11085056,
        max: 11085312,
        name: "RSHIFTR",
    },
    {
        min: 11085312,
        max: 11085568,
        name: "RSHIFTC",
    },
    {
        min: 11085824,
        max: 11086080,
        name: "MODPOW2",
    },
    {
        min: 11086080,
        max: 11086336,
        name: "MODPOW2R",
    },
    {
        min: 11086336,
        max: 11086592,
        name: "MODPOW2C",
    },
    {
        min: 11086848,
        max: 11087104,
        name: "RSHIFTMOD",
    },
    {
        min: 11087104,
        max: 11087360,
        name: "RSHIFTMODR",
    },
    {
        min: 11087360,
        max: 11087616,
        name: "RSHIFTMODC",
    },
    {
        min: 12036384,
        max: 12036385,
        name: "QADDRSHIFTMOD",
    },
    {
        min: 12036385,
        max: 12036386,
        name: "QADDRSHIFTMODR",
    },
    {
        min: 12036386,
        max: 12036387,
        name: "QADDRSHIFTMODC",
    },
    {
        min: 12036389,
        max: 12036390,
        name: "QRSHIFTR",
    },
    {
        min: 12036390,
        max: 12036391,
        name: "QRSHIFTC",
    },
    {
        min: 12036392,
        max: 12036393,
        name: "QMODPOW2",
    },
    {
        min: 12036393,
        max: 12036394,
        name: "QMODPOW2R",
    },
    {
        min: 12036394,
        max: 12036395,
        name: "QMODPOW2C",
    },
    {
        min: 12036396,
        max: 12036397,
        name: "QRSHIFTMOD",
    },
    {
        min: 12036397,
        max: 12036398,
        name: "QRSHIFTMODR",
    },
    {
        min: 12036398,
        max: 12036399,
        name: "QRSHIFTMODC",
    },
    {
        min: 11108352,
        max: 11108608,
        name: "MULADDDIVMOD",
    },
    {
        min: 11108608,
        max: 11108864,
        name: "MULADDDIVMODR",
    },
    {
        min: 11108864,
        max: 11109120,
        name: "MULADDDIVMODC",
    },
    {
        min: 11109376,
        max: 11109632,
        name: "MULDIV",
    },
    {
        min: 11109632,
        max: 11109888,
        name: "MULDIVR",
    },
    {
        min: 11109888,
        max: 11110144,
        name: "MULDIVC",
    },
    {
        min: 11110400,
        max: 11110656,
        name: "MULMOD",
    },
    {
        min: 11110656,
        max: 11110912,
        name: "MULMODR",
    },
    {
        min: 11110912,
        max: 11111168,
        name: "MULMODC",
    },
    {
        min: 11111424,
        max: 11111680,
        name: "MULDIVMOD",
    },
    {
        min: 11111680,
        max: 11111936,
        name: "MULDIVMODR",
    },
    {
        min: 11111936,
        max: 11112192,
        name: "MULDIVMODC",
    },
    {
        min: 12036480,
        max: 12036481,
        name: "QMULADDDIVMOD",
    },
    {
        min: 12036481,
        max: 12036482,
        name: "QMULADDDIVMODR",
    },
    {
        min: 12036482,
        max: 12036483,
        name: "QMULADDDIVMODC",
    },
    {
        min: 12036484,
        max: 12036485,
        name: "QMULDIV",
    },
    {
        min: 12036485,
        max: 12036486,
        name: "QMULDIVR",
    },
    {
        min: 12036486,
        max: 12036487,
        name: "QMULDIVC",
    },
    {
        min: 12036488,
        max: 12036489,
        name: "QMULMOD",
    },
    {
        min: 12036489,
        max: 12036490,
        name: "QMULMODR",
    },
    {
        min: 12036490,
        max: 12036491,
        name: "QMULMODC",
    },
    {
        min: 12036492,
        max: 12036493,
        name: "QMULDIVMOD",
    },
    {
        min: 12036493,
        max: 12036494,
        name: "QMULDIVMODR",
    },
    {
        min: 12036494,
        max: 12036495,
        name: "QMULDIVMODC",
    },
    {
        min: 11116544,
        max: 11116800,
        name: "MULADDRSHIFTMOD",
    },
    {
        min: 11116800,
        max: 11117056,
        name: "MULADDRSHIFTRMOD",
    },
    {
        min: 11117056,
        max: 11117312,
        name: "MULADDRSHIFTCMOD",
    },
    {
        min: 11117568,
        max: 11117824,
        name: "MULRSHIFT",
    },
    {
        min: 11117824,
        max: 11118080,
        name: "MULRSHIFTR",
    },
    {
        min: 11118080,
        max: 11118336,
        name: "MULRSHIFTC",
    },
    {
        min: 11118592,
        max: 11118848,
        name: "MULMODPOW2",
    },
    {
        min: 11118848,
        max: 11119104,
        name: "MULMODPOW2R",
    },
    {
        min: 11119104,
        max: 11119360,
        name: "MULMODPOW2C",
    },
    {
        min: 11119616,
        max: 11119872,
        name: "MULRSHIFTMOD",
    },
    {
        min: 11119872,
        max: 11120128,
        name: "MULRSHIFTRMOD",
    },
    {
        min: 11120128,
        max: 11120384,
        name: "MULRSHIFTCMOD",
    },
    {
        min: 12036512,
        max: 12036513,
        name: "QMULADDRSHIFTMOD",
    },
    {
        min: 12036513,
        max: 12036514,
        name: "QMULADDRSHIFTRMOD",
    },
    {
        min: 12036514,
        max: 12036515,
        name: "QMULADDRSHIFTCMOD",
    },
    {
        min: 12036516,
        max: 12036517,
        name: "QMULRSHIFT",
    },
    {
        min: 12036517,
        max: 12036518,
        name: "QMULRSHIFTR",
    },
    {
        min: 12036518,
        max: 12036519,
        name: "QMULRSHIFTC",
    },
    {
        min: 12036520,
        max: 12036521,
        name: "QMULMODPOW2",
    },
    {
        min: 12036521,
        max: 12036522,
        name: "QMULMODPOW2R",
    },
    {
        min: 12036522,
        max: 12036523,
        name: "QMULMODPOW2C",
    },
    {
        min: 12036524,
        max: 12036525,
        name: "QMULRSHIFTMOD",
    },
    {
        min: 12036525,
        max: 12036526,
        name: "QMULRSHIFTRMOD",
    },
    {
        min: 12036526,
        max: 12036527,
        name: "QMULRSHIFTCMOD",
    },
    {
        min: 11124736,
        max: 11124992,
        name: "LSHIFTADDDIVMOD",
    },
    {
        min: 11124992,
        max: 11125248,
        name: "LSHIFTADDDIVMODR",
    },
    {
        min: 11125248,
        max: 11125504,
        name: "LSHIFTADDDIVMODC",
    },
    {
        min: 11125760,
        max: 11126016,
        name: "LSHIFTDIV",
    },
    {
        min: 11126016,
        max: 11126272,
        name: "LSHIFTDIVR",
    },
    {
        min: 11126272,
        max: 11126528,
        name: "LSHIFTDIVC",
    },
    {
        min: 11126784,
        max: 11127040,
        name: "LSHIFTMOD",
    },
    {
        min: 11127040,
        max: 11127296,
        name: "LSHIFTMODR",
    },
    {
        min: 11127296,
        max: 11127552,
        name: "LSHIFTMODC",
    },
    {
        min: 11127808,
        max: 11128064,
        name: "LSHIFTDIVMOD",
    },
    {
        min: 11128064,
        max: 11128320,
        name: "LSHIFTDIVMODR",
    },
    {
        min: 11128320,
        max: 11128576,
        name: "LSHIFTDIVMODC",
    },
    {
        min: 12036544,
        max: 12036545,
        name: "QLSHIFTADDDIVMOD",
    },
    {
        min: 12036545,
        max: 12036546,
        name: "QLSHIFTADDDIVMODR",
    },
    {
        min: 12036546,
        max: 12036547,
        name: "QLSHIFTADDDIVMODC",
    },
    {
        min: 12036548,
        max: 12036549,
        name: "QLSHIFTDIV",
    },
    {
        min: 12036549,
        max: 12036550,
        name: "QLSHIFTDIVR",
    },
    {
        min: 12036550,
        max: 12036551,
        name: "QLSHIFTDIVC",
    },
    {
        min: 12036552,
        max: 12036553,
        name: "QLSHIFTMOD",
    },
    {
        min: 12036553,
        max: 12036554,
        name: "QLSHIFTMODR",
    },
    {
        min: 12036554,
        max: 12036555,
        name: "QLSHIFTMODC",
    },
    {
        min: 12036556,
        max: 12036557,
        name: "QLSHIFTDIVMOD",
    },
    {
        min: 12036557,
        max: 12036558,
        name: "QLSHIFTDIVMODR",
    },
    {
        min: 12036558,
        max: 12036559,
        name: "QLSHIFTDIVMODC",
    },
    {
        min: 13565952,
        max: 13566208,
        name: "STIX",
    },
    {
        min: 13566208,
        max: 13566464,
        name: "STUX",
    },
    {
        min: 13566464,
        max: 13566720,
        name: "STIXR",
    },
    {
        min: 13566720,
        max: 13566976,
        name: "STUXR",
    },
    {
        min: 13566976,
        max: 13567232,
        name: "STIXQ",
    },
    {
        min: 13567232,
        max: 13567488,
        name: "STUXQ",
    },
    {
        min: 13567488,
        max: 13567744,
        name: "STIXRQ",
    },
    {
        min: 13567744,
        max: 13568000,
        name: "STUXRQ",
    },
    {
        min: 13576192,
        max: 13576448,
        name: "STILE4",
    },
    {
        min: 13576448,
        max: 13576704,
        name: "STULE4",
    },
    {
        min: 13576704,
        max: 13576960,
        name: "STILE8",
    },
    {
        min: 13576960,
        max: 13577216,
        name: "STULE8",
    },
    {
        min: 14090240,
        max: 14090496,
        name: "LDIX",
    },
    {
        min: 14090496,
        max: 14090752,
        name: "LDUX",
    },
    {
        min: 14090752,
        max: 14091008,
        name: "PLDIX",
    },
    {
        min: 14091008,
        max: 14091264,
        name: "PLDUX",
    },
    {
        min: 14091264,
        max: 14091520,
        name: "LDIXQ",
    },
    {
        min: 14091520,
        max: 14091776,
        name: "LDUXQ",
    },
    {
        min: 14091776,
        max: 14092032,
        name: "PLDIXQ",
    },
    {
        min: 14092032,
        max: 14092288,
        name: "PLDUXQ",
    },
    {
        min: 14096384,
        max: 14096640,
        name: "LDSLICEX",
    },
    {
        min: 14096640,
        max: 14096896,
        name: "PLDSLICEX",
    },
    {
        min: 14096896,
        max: 14097152,
        name: "LDSLICEXQ",
    },
    {
        min: 14097152,
        max: 14097408,
        name: "PLDSLICEXQ",
    },
    {
        min: 14110720,
        max: 14110976,
        name: "LDILE4",
    },
    {
        min: 14110976,
        max: 14111232,
        name: "LDULE4",
    },
    {
        min: 14111232,
        max: 14111488,
        name: "LDILE8",
    },
    {
        min: 14111488,
        max: 14111744,
        name: "LDULE8",
    },
    {
        min: 14111744,
        max: 14112000,
        name: "PLDILE4",
    },
    {
        min: 14112000,
        max: 14112256,
        name: "PLDULE4",
    },
    {
        min: 14112256,
        max: 14112512,
        name: "PLDILE8",
    },
    {
        min: 14112512,
        max: 14112768,
        name: "PLDULE8",
    },
    {
        min: 14112768,
        max: 14113024,
        name: "LDILE4Q",
    },
    {
        min: 14113024,
        max: 14113280,
        name: "LDULE4Q",
    },
    {
        min: 14113280,
        max: 14113536,
        name: "LDILE8Q",
    },
    {
        min: 14113536,
        max: 14113792,
        name: "LDULE8Q",
    },
    {
        min: 14113792,
        max: 14114048,
        name: "PLDILE4Q",
    },
    {
        min: 14114048,
        max: 14114304,
        name: "PLDULE4Q",
    },
    {
        min: 14114304,
        max: 14114560,
        name: "PLDILE8Q",
    },
    {
        min: 14114560,
        max: 14114816,
        name: "PLDULE8Q",
    },
    {
        min: 16031744,
        max: 16032000,
        name: "DICTIGETJMP",
    },
    {
        min: 16032000,
        max: 16032256,
        name: "DICTUGETJMP",
    },
    {
        min: 16032256,
        max: 16032512,
        name: "DICTIGETEXEC",
    },
    {
        min: 16032512,
        max: 16032768,
        name: "DICTUGETEXEC",
    },
    {
        min: 16038912,
        max: 16039168,
        name: "DICTIGETJMPZ",
    },
    {
        min: 16039168,
        max: 16039424,
        name: "DICTUGETJMPZ",
    },
    {
        min: 16039424,
        max: 16039680,
        name: "DICTIGETEXECZ",
    },
    {
        min: 16039680,
        max: 16039936,
        name: "DICTUGETEXECZ",
    },
    {
        min: 15993344,
        max: 15993600,
        name: "DICTGET",
    },
    {
        min: 15993600,
        max: 15993856,
        name: "DICTGETREF",
    },
    {
        min: 15993856,
        max: 15994112,
        name: "DICTIGET",
    },
    {
        min: 15994112,
        max: 15994368,
        name: "DICTIGETREF",
    },
    {
        min: 15994368,
        max: 15994624,
        name: "DICTUGET",
    },
    {
        min: 15994624,
        max: 15994880,
        name: "DICTUGETREF",
    },
    {
        min: 15995392,
        max: 15995648,
        name: "DICTSET",
    },
    {
        min: 15995648,
        max: 15995904,
        name: "DICTSETREF",
    },
    {
        min: 15995904,
        max: 15996160,
        name: "DICTISET",
    },
    {
        min: 15996160,
        max: 15996416,
        name: "DICTISETREF",
    },
    {
        min: 15996416,
        max: 15996672,
        name: "DICTUSET",
    },
    {
        min: 15996672,
        max: 15996928,
        name: "DICTUSETREF",
    },
    {
        min: 15997440,
        max: 15997696,
        name: "DICTSETGET",
    },
    {
        min: 15997696,
        max: 15997952,
        name: "DICTSETGETREF",
    },
    {
        min: 15997952,
        max: 15998208,
        name: "DICTISETGET",
    },
    {
        min: 15998208,
        max: 15998464,
        name: "DICTISETGETREF",
    },
    {
        min: 15998464,
        max: 15998720,
        name: "DICTUSETGET",
    },
    {
        min: 15998720,
        max: 15998976,
        name: "DICTUSETGETREF",
    },
    {
        min: 15999488,
        max: 15999744,
        name: "DICTREPLACE",
    },
    {
        min: 15999744,
        max: 16000000,
        name: "DICTREPLACEREF",
    },
    {
        min: 16000000,
        max: 16000256,
        name: "DICTIREPLACE",
    },
    {
        min: 16000256,
        max: 16000512,
        name: "DICTIREPLACEREF",
    },
    {
        min: 16000512,
        max: 16000768,
        name: "DICTUREPLACE",
    },
    {
        min: 16000768,
        max: 16001024,
        name: "DICTUREPLACEREF",
    },
    {
        min: 16001536,
        max: 16001792,
        name: "DICTREPLACEGET",
    },
    {
        min: 16001792,
        max: 16002048,
        name: "DICTREPLACEGETREF",
    },
    {
        min: 16002048,
        max: 16002304,
        name: "DICTIREPLACEGET",
    },
    {
        min: 16002304,
        max: 16002560,
        name: "DICTIREPLACEGETREF",
    },
    {
        min: 16002560,
        max: 16002816,
        name: "DICTUREPLACEGET",
    },
    {
        min: 16002816,
        max: 16003072,
        name: "DICTUREPLACEGETREF",
    },
    {
        min: 16003584,
        max: 16003840,
        name: "DICTADD",
    },
    {
        min: 16003840,
        max: 16004096,
        name: "DICTADDREF",
    },
    {
        min: 16004096,
        max: 16004352,
        name: "DICTIADD",
    },
    {
        min: 16004352,
        max: 16004608,
        name: "DICTIADDREF",
    },
    {
        min: 16004608,
        max: 16004864,
        name: "DICTUADD",
    },
    {
        min: 16004864,
        max: 16005120,
        name: "DICTUADDREF",
    },
    {
        min: 16005632,
        max: 16005888,
        name: "DICTADDGET",
    },
    {
        min: 16005888,
        max: 16006144,
        name: "DICTADDGETREF",
    },
    {
        min: 16006144,
        max: 16006400,
        name: "DICTIADDGET",
    },
    {
        min: 16006400,
        max: 16006656,
        name: "DICTIADDGETREF",
    },
    {
        min: 16006656,
        max: 16006912,
        name: "DICTUADDGET",
    },
    {
        min: 16006912,
        max: 16007168,
        name: "DICTUADDGETREF",
    },
    {
        min: 16015872,
        max: 16016128,
        name: "DICTDELGET",
    },
    {
        min: 16016128,
        max: 16016384,
        name: "DICTDELGETREF",
    },
    {
        min: 16016384,
        max: 16016640,
        name: "DICTIDELGET",
    },
    {
        min: 16016640,
        max: 16016896,
        name: "DICTIDELGETREF",
    },
    {
        min: 16016896,
        max: 16017152,
        name: "DICTUDELGET",
    },
    {
        min: 16017152,
        max: 16017408,
        name: "DICTUDELGETREF",
    },
    {
        min: 16024064,
        max: 16024320,
        name: "DICTMIN",
    },
    {
        min: 16024320,
        max: 16024576,
        name: "DICTMINREF",
    },
    {
        min: 16024576,
        max: 16024832,
        name: "DICTIMIN",
    },
    {
        min: 16024832,
        max: 16025088,
        name: "DICTIMINREF",
    },
    {
        min: 16025088,
        max: 16025344,
        name: "DICTUMIN",
    },
    {
        min: 16025344,
        max: 16025600,
        name: "DICTUMINREF",
    },
    {
        min: 16026112,
        max: 16026368,
        name: "DICTMAX",
    },
    {
        min: 16026368,
        max: 16026624,
        name: "DICTMAXREF",
    },
    {
        min: 16026624,
        max: 16026880,
        name: "DICTIMAX",
    },
    {
        min: 16026880,
        max: 16027136,
        name: "DICTIMAXREF",
    },
    {
        min: 16027136,
        max: 16027392,
        name: "DICTUMAX",
    },
    {
        min: 16027392,
        max: 16027648,
        name: "DICTUMAXREF",
    },
    {
        min: 16028160,
        max: 16028416,
        name: "DICTREMMIN",
    },
    {
        min: 16028416,
        max: 16028672,
        name: "DICTREMMINREF",
    },
    {
        min: 16028672,
        max: 16028928,
        name: "DICTIREMMIN",
    },
    {
        min: 16028928,
        max: 16029184,
        name: "DICTIREMMINREF",
    },
    {
        min: 16029184,
        max: 16029440,
        name: "DICTUREMMIN",
    },
    {
        min: 16029440,
        max: 16029696,
        name: "DICTUREMMINREF",
    },
    {
        min: 16030208,
        max: 16030464,
        name: "DICTREMMAX",
    },
    {
        min: 16030464,
        max: 16030720,
        name: "DICTREMMAXREF",
    },
    {
        min: 16030720,
        max: 16030976,
        name: "DICTIREMMAX",
    },
    {
        min: 16030976,
        max: 16031232,
        name: "DICTIREMMAXREF",
    },
    {
        min: 16031232,
        max: 16031488,
        name: "DICTUREMMAX",
    },
    {
        min: 16031488,
        max: 16031744,
        name: "DICTUREMMAXREF",
    },
    {
        min: 16007424,
        max: 16007680,
        name: "DICTSETB",
    },
    {
        min: 16007680,
        max: 16007936,
        name: "DICTISETB",
    },
    {
        min: 16007936,
        max: 16008192,
        name: "DICTUSETB",
    },
    {
        min: 16008448,
        max: 16008704,
        name: "DICTSETGETB",
    },
    {
        min: 16008704,
        max: 16008960,
        name: "DICTISETGETB",
    },
    {
        min: 16008960,
        max: 16009216,
        name: "DICTUSETGETB",
    },
    {
        min: 16009472,
        max: 16009728,
        name: "DICTREPLACEB",
    },
    {
        min: 16009728,
        max: 16009984,
        name: "DICTIREPLACEB",
    },
    {
        min: 16009984,
        max: 16010240,
        name: "DICTUREPLACEB",
    },
    {
        min: 16010496,
        max: 16010752,
        name: "DICTREPLACEGETB",
    },
    {
        min: 16010752,
        max: 16011008,
        name: "DICTIREPLACEGETB",
    },
    {
        min: 16011008,
        max: 16011264,
        name: "DICTUREPLACEGETB",
    },
    {
        min: 16011520,
        max: 16011776,
        name: "DICTADDB",
    },
    {
        min: 16011776,
        max: 16012032,
        name: "DICTIADDB",
    },
    {
        min: 16012032,
        max: 16012288,
        name: "DICTUADDB",
    },
    {
        min: 16012544,
        max: 16012800,
        name: "DICTADDGETB",
    },
    {
        min: 16012800,
        max: 16013056,
        name: "DICTIADDGETB",
    },
    {
        min: 16013056,
        max: 16013312,
        name: "DICTUADDGETB",
    },
    {
        min: 16013568,
        max: 16013824,
        name: "DICTDEL",
    },
    {
        min: 16013824,
        max: 16014080,
        name: "DICTIDEL",
    },
    {
        min: 16014080,
        max: 16014336,
        name: "DICTUDEL",
    },
    {
        min: 16017664,
        max: 16017920,
        name: "DICTGETOPTREF",
    },
    {
        min: 16017920,
        max: 16018176,
        name: "DICTIGETOPTREF",
    },
    {
        min: 16018176,
        max: 16018432,
        name: "DICTUGETOPTREF",
    },
    {
        min: 16018688,
        max: 16018944,
        name: "DICTSETGETOPTREF",
    },
    {
        min: 16018944,
        max: 16019200,
        name: "DICTISETGETOPTREF",
    },
    {
        min: 16019200,
        max: 16019456,
        name: "DICTUSETGETOPTREF",
    },
    {
        min: 16036096,
        max: 16036352,
        name: "SUBDICTGET",
    },
    {
        min: 16036352,
        max: 16036608,
        name: "SUBDICTIGET",
    },
    {
        min: 16036608,
        max: 16036864,
        name: "SUBDICTUGET",
    },
    {
        min: 16037120,
        max: 16037376,
        name: "SUBDICTRPGET",
    },
    {
        min: 16037376,
        max: 16037632,
        name: "SUBDICTIRPGET",
    },
    {
        min: 16037632,
        max: 16037888,
        name: "SUBDICTURPGET",
    },
    {
        min: 15921152,
        max: 15921408,
        name: "THROWANY",
    },
    {
        min: 15921408,
        max: 15921664,
        name: "THROWARGANY",
    },
    {
        min: 15922176,
        max: 15922432,
        name: "THROWANYIFNOT",
    },
    {
        min: 15922432,
        max: 15922688,
        name: "THROWARGANYIFNOT",
    },
    {
        min: 16020480,
        max: 16020736,
        name: "DICTGETNEXT",
    },
    {
        min: 16020736,
        max: 16020992,
        name: "DICTGETNEXTEQ",
    },
    {
        min: 16020992,
        max: 16021248,
        name: "DICTGETPREV",
    },
    {
        min: 16021248,
        max: 16021504,
        name: "DICTGETPREVEQ",
    },
    {
        min: 16021504,
        max: 16021760,
        name: "DICTIGETNEXT",
    },
    {
        min: 16021760,
        max: 16022016,
        name: "DICTIGETNEXTEQ",
    },
    {
        min: 16022016,
        max: 16022272,
        name: "DICTIGETPREV",
    },
    {
        min: 16022272,
        max: 16022528,
        name: "DICTIGETPREVEQ",
    },
    {
        min: 16022528,
        max: 16022784,
        name: "DICTUGETNEXT",
    },
    {
        min: 16022784,
        max: 16023040,
        name: "DICTUGETNEXTEQ",
    },
    {
        min: 16023040,
        max: 16023296,
        name: "DICTUGETPREV",
    },
    {
        min: 16023296,
        max: 16023552,
        name: "DICTUGETPREVEQ",
    },
    {
        min: 10878976,
        max: 10944512,
        name: "ADDINT",
    },
    {
        min: 10944512,
        max: 11010048,
        name: "MULINT",
    },
    {
        min: 12035584,
        max: 12035840,
        name: "QADDINT",
    },
    {
        min: 12035840,
        max: 12036096,
        name: "QMULINT",
    },
    {
        min: 12582912,
        max: 12648448,
        name: "EQINT",
    },
    {
        min: 12648448,
        max: 12713984,
        name: "LESSINT",
    },
    {
        min: 12713984,
        max: 12779520,
        name: "GTINT",
    },
    {
        min: 12779520,
        max: 12845056,
        name: "NEQINT",
    },
    {
        min: 12042240,
        max: 12042496,
        name: "QEQINT",
    },
    {
        min: 12042496,
        max: 12042752,
        name: "QLESSINT",
    },
    {
        min: 12042752,
        max: 12043008,
        name: "QGTINT",
    },
    {
        min: 12043008,
        max: 12043264,
        name: "QNEQINT",
    },
    {
        min: 8650752,
        max: 8716288,
        name: "PUSHPOW2DEC",
    },
    {
        min: 8716288,
        max: 8781824,
        name: "PUSHNEGPOW2",
    },
    {
        min: 11796480,
        max: 11862016,
        name: "FITS",
    },
    {
        min: 11862016,
        max: 11927552,
        name: "UFITS",
    },
    {
        min: 12039168,
        max: 12039424,
        name: "QFITS",
    },
    {
        min: 12039424,
        max: 12039680,
        name: "QUFITS",
    },
    {
        min: 15590144,
        max: 15590400,
        name: "SETCONTCTRMANY",
    },
    {
        min: 14366208,
        max: 14366464,
        name: "CALLCCARGS",
    },
    {
        min: 15925248,
        max: 15990784,
        name: "TRYARGS",
    },
    {
        min: 14109696,
        max: 14110720,
        name: "PLDREFIDX",
    },
    {
        min: 14116864,
        max: 14117888,
        name: "CHASHI",
    },
    {
        min: 14117888,
        max: 14118912,
        name: "CDEPTHI",
    },
    {
        min: 15810560,
        max: 15826944,
        name: "JMPDICT",
    },
    {
        min: 15826944,
        max: 15843328,
        name: "PREPAREDICT",
    },
    {
        min: 15910912,
        max: 15912960,
        name: "THROWARG",
    },
    {
        min: 15915008,
        max: 15917056,
        name: "THROWARGIF",
    },
    {
        min: 15919104,
        max: 15921152,
        name: "THROWARGIFNOT",
    },
    {
        min: 14356480,
        max: 14360576,
        name: "JMPXARGS",
    },
    {
        min: 14360576,
        max: 14364672,
        name: "RETARGS",
    },
    {
        min: 15532032,
        max: 15536128,
        name: "RETURNARGS",
    },
    {
        min: 6225920,
        max: 6230016,
        name: "BLKDROP",
    },
    {
        min: 7274496,
        max: 7278592,
        name: "TUPLE",
    },
    {
        min: 7278592,
        max: 7282688,
        name: "INDEX",
    },
    {
        min: 7282688,
        max: 7286784,
        name: "UNTUPLE",
    },
    {
        min: 7286784,
        max: 7290880,
        name: "UNPACKFIRST",
    },
    {
        min: 7290880,
        max: 7294976,
        name: "EXPLODE",
    },
    {
        min: 7294976,
        max: 7299072,
        name: "SETINDEX",
    },
    {
        min: 7299072,
        max: 7303168,
        name: "INDEXQ",
    },
    {
        min: 7303168,
        max: 7307264,
        name: "SETINDEXQ",
    },
    {
        min: 5509120,
        max: 5513216,
        name: "XC2PU",
    },
    {
        min: 5517312,
        max: 5521408,
        name: "XCPU2",
    },
    {
        min: 5533696,
        max: 5537792,
        name: "PUSH3",
    },
    {
        min: 5242880,
        max: 5308416,
        name: "XCHG2",
    },
    {
        min: 5308416,
        max: 5373952,
        name: "XCPU",
    },
    {
        min: 5439488,
        max: 5505024,
        name: "PUSH2",
    },
    {
        min: 5373952,
        max: 5439488,
        name: "PUXC",
    },
    {
        min: 5513216,
        max: 5517312,
        name: "XCPUXC",
    },
    {
        min: 5521408,
        max: 5525504,
        name: "PUXC2",
    },
    {
        min: 5525504,
        max: 5529600,
        name: "PUXCPU",
    },
    {
        min: 5529600,
        max: 5533696,
        name: "PU2XC",
    },
    {
        min: 5570560,
        max: 5636096,
        name: "BLKSWAP",
    },
    {
        min: 6160384,
        max: 6225920,
        name: "REVERSE",
    },
    {
        min: 15466496,
        max: 15532032,
        name: "SETCONTARGS",
    },
    {
        min: 15597568,
        max: 15663104,
        name: "BLESSARGS",
    },
    {
        min: 13568512,
        max: 13568768,
        name: "STIR",
    },
    {
        min: 13568768,
        max: 13569024,
        name: "STUR",
    },
    {
        min: 13569024,
        max: 13569280,
        name: "STIQ",
    },
    {
        min: 13569280,
        max: 13569536,
        name: "STUQ",
    },
    {
        min: 13569536,
        max: 13569792,
        name: "STIRQ",
    },
    {
        min: 13569792,
        max: 13570048,
        name: "STURQ",
    },
    {
        min: 14092800,
        max: 14093056,
        name: "PLDI",
    },
    {
        min: 14093056,
        max: 14093312,
        name: "PLDU",
    },
    {
        min: 14093312,
        max: 14093568,
        name: "LDIQ",
    },
    {
        min: 14093568,
        max: 14093824,
        name: "LDUQ",
    },
    {
        min: 14093824,
        max: 14094080,
        name: "PLDIQ",
    },
    {
        min: 14094080,
        max: 14094336,
        name: "PLDUQ",
    },
    {
        min: 14094336,
        max: 14096384,
        name: "PLDUZ",
    },
    {
        min: 14097664,
        max: 14097920,
        name: "PLDSLICE",
    },
    {
        min: 14097920,
        max: 14098176,
        name: "LDSLICEQ",
    },
    {
        min: 14098176,
        max: 14098432,
        name: "PLDSLICEQ",
    },
    {
        min: 14909440,
        max: 14917632,
        name: "IFBITJMP",
    },
    {
        min: 14917632,
        max: 14925824,
        name: "IFNBITJMP",
    },
    {
        min: 7319552,
        max: 7323648,
        name: "INDEX2",
    },
    {
        min: 7323648,
        max: 7340032,
        name: "INDEX3",
    },
    {
        min: 8585216,
        max: 8650496,
        name: "PUSHPOW2",
    },
    {
        min: 6230016,
        max: 6291456,
        name: "BLKPUSH",
    },
    {
        min: 7081984,
        max: 7143424,
        name: "BLKDROP2",
    },
    {
        min: 16269568,
        max: 16277504,
        name: "GETGLOB",
    },
    {
        min: 16277760,
        max: 16285696,
        name: "SETGLOB",
    },
    {
        min: 16261120,
        max: 16261888,
        name: "GETPARAM",
    },
    {
        min: 8912896,
        max: 8978432,
        name: "PUSHREF",
    },
    {
        min: 8978432,
        max: 9043968,
        name: "PUSHREFSLICE",
    },
    {
        min: 9043968,
        max: 9109504,
        name: "PUSHREFCONT",
    },
    {
        min: 14367744,
        max: 14368000,
        name: "CALLREF",
    },
    {
        min: 14368000,
        max: 14368256,
        name: "JMPREF",
    },
    {
        min: 14368256,
        max: 14368512,
        name: "JMPREFDATA",
    },
    {
        min: 14876672,
        max: 14876928,
        name: "IFREF",
    },
    {
        min: 14876928,
        max: 14877184,
        name: "IFNOTREF",
    },
    {
        min: 14877184,
        max: 14877440,
        name: "IFJMPREF",
    },
    {
        min: 14877440,
        max: 14877696,
        name: "IFNOTJMPREF",
    },
    {
        min: 14880000,
        max: 14880256,
        name: "IFREFELSE",
    },
    {
        min: 14880256,
        max: 14880512,
        name: "IFELSEREF",
    },
    {
        min: 14880512,
        max: 14880768,
        name: "IFREFELSEREF",
    },
    {
        min: 14925824,
        max: 14934016,
        name: "IFBITJMPREF",
    },
    {
        min: 14934016,
        max: 14942208,
        name: "IFNBITJMPREF",
    },
    {
        min: 16032768,
        max: 16033792,
        name: "DICTPUSHCONST",
    },
    {
        min: 16034816,
        max: 16035840,
        name: "PFXDICTSWITCH",
    },
    {
        min: 14099968,
        max: 14100224,
        name: "SDBEGINSX",
    },
    {
        min: 14100224,
        max: 14100480,
        name: "SDBEGINSXQ",
    },
    {
        min: 14100480,
        max: 14101504,
        name: "SDBEGINS",
    },
    {
        min: 14101504,
        max: 14102528,
        name: "SDBEGINSQ",
    },
    {
        min: 13574144,
        max: 13574400,
        name: "STREFCONST",
    },
    {
        min: 13574400,
        max: 13574656,
        name: "STREF2CONST",
    },
    {
        min: 15921664,
        max: 15921920,
        name: "THROWANYIF",
    },
    {
        min: 15921920,
        max: 15922176,
        name: "THROWARGANYIF",
    },
    {
        min: 16707584,
        max: 16711680,
        name: "DEBUGSTR",
    },
    {
        min: 15556608,
        max: 15558656,
        name: "SETCONTCTR",
    },
    {
        min: 15560704,
        max: 15562752,
        name: "SETRETCTR",
    },
    {
        min: 15564800,
        max: 15566848,
        name: "SETALTCTR",
    },
    {
        min: 15568896,
        max: 15570944,
        name: "POPSAVE",
    },
    {
        min: 15572992,
        max: 15575040,
        name: "SAVECTR",
    },
    {
        min: 15577088,
        max: 15579136,
        name: "SAVEALTCTR",
    },
    {
        min: 15581184,
        max: 15583232,
        name: "SAVEBOTHCTR",
    },
    {
        min: 14368768,
        max: 14372864,
        name: "RUNVM",
    },
    {
        min: 5898240,
        max: 5963776,
        name: "SWAP2",
    },
    {
        min: 5963776,
        max: 6029312,
        name: "DROP2",
    },
    {
        min: 6029312,
        max: 6094848,
        name: "DUP2",
    },
    {
        min: 6094848,
        max: 6160384,
        name: "OVER2",
    },
    {
        min: 11087872,
        max: 11088128,
        name: "ADDRSHIFT_MOD",
    },
    {
        min: 11088128,
        max: 11088384,
        name: "ADDRSHIFTR_MOD",
    },
    {
        min: 11088384,
        max: 11088640,
        name: "ADDRSHIFTC_MOD",
    },
    {
        min: 11088896,
        max: 11089152,
        name: "RSHIFT_",
    },
    {
        min: 11089152,
        max: 11089408,
        name: "RSHIFTR_",
    },
    {
        min: 11089408,
        max: 11089664,
        name: "RSHIFTC_",
    },
    {
        min: 11089920,
        max: 11090176,
        name: "MODPOW2_",
    },
    {
        min: 11090176,
        max: 11090432,
        name: "MODPOW2R_",
    },
    {
        min: 11090432,
        max: 11090688,
        name: "MODPOW2C_",
    },
    {
        min: 11090944,
        max: 11091200,
        name: "RSHIFT_MOD",
    },
    {
        min: 11091200,
        max: 11091456,
        name: "RSHIFTR_MOD",
    },
    {
        min: 11091456,
        max: 11091712,
        name: "RSHIFTC_MOD",
    },
    {
        min: 11120640,
        max: 11120896,
        name: "MULADDRSHIFT_MOD",
    },
    {
        min: 11120896,
        max: 11121152,
        name: "MULADDRSHIFTR_MOD",
    },
    {
        min: 11121152,
        max: 11121408,
        name: "MULADDRSHIFTC_MOD",
    },
    {
        min: 11121664,
        max: 11121920,
        name: "MULRSHIFT_",
    },
    {
        min: 11121920,
        max: 11122176,
        name: "MULRSHIFTR_",
    },
    {
        min: 11122176,
        max: 11122432,
        name: "MULRSHIFTC_",
    },
    {
        min: 11122688,
        max: 11122944,
        name: "MULMODPOW2_",
    },
    {
        min: 11122944,
        max: 11123200,
        name: "MULMODPOW2R_",
    },
    {
        min: 11123200,
        max: 11123456,
        name: "MULMODPOW2C_",
    },
    {
        min: 11123712,
        max: 11123968,
        name: "MULRSHIFT_MOD",
    },
    {
        min: 11123968,
        max: 11124224,
        name: "MULRSHIFTR_MOD",
    },
    {
        min: 11124224,
        max: 11124480,
        name: "MULRSHIFTC_MOD",
    },
    {
        min: 11128832,
        max: 11129088,
        name: "LSHIFT_ADDDIVMOD",
    },
    {
        min: 11129088,
        max: 11129344,
        name: "LSHIFT_ADDDIVMODR",
    },
    {
        min: 11129344,
        max: 11129600,
        name: "LSHIFT_ADDDIVMODC",
    },
    {
        min: 11129856,
        max: 11130112,
        name: "LSHIFT_DIV",
    },
    {
        min: 11130112,
        max: 11130368,
        name: "LSHIFT_DIVR",
    },
    {
        min: 11130368,
        max: 11130624,
        name: "LSHIFT_DIVC",
    },
    {
        min: 11130880,
        max: 11131136,
        name: "LSHIFT_MOD",
    },
    {
        min: 11131136,
        max: 11131392,
        name: "LSHIFT_MODR",
    },
    {
        min: 11131392,
        max: 11131648,
        name: "LSHIFT_MODC",
    },
    {
        min: 11131904,
        max: 11132160,
        name: "LSHIFT_DIVMOD",
    },
    {
        min: 11132160,
        max: 11132416,
        name: "LSHIFT_DIVMODR",
    },
    {
        min: 11132416,
        max: 11132672,
        name: "LSHIFT_DIVMODC",
    },
    {
        min: 16319488,
        max: 16319744,
        name: "HASHEXT",
    },
    {
        min: 16319744,
        max: 16320000,
        name: "HASHEXTR",
    },
    {
        min: 16320000,
        max: 16320256,
        name: "HASHEXTA",
    },
    {
        min: 16320256,
        max: 16320512,
        name: "HASHEXTAR",
    },
    {
        min: 13369344,
        max: 13434880,
        name: "STREF",
    },
    {
        min: 13570048,
        max: 13570304,
        name: "STREF_ALT",
    },
    {
        min: 13500416,
        max: 13565952,
        name: "STSLICE",
    },
    {
        min: 13570560,
        max: 13570816,
        name: "STSLICE_ALT",
    },
    {
        min: 4194304,
        max: 5242880,
        name: "XCHG3",
    },
    {
        min: 5505024,
        max: 5509120,
        name: "XCHG3_ALT",
    },
    {
        min: 13238272,
        max: 13303808,
        name: "STI",
    },
    {
        min: 13568000,
        max: 13568256,
        name: "STI_ALT",
    },
    {
        min: 13303808,
        max: 13369344,
        name: "STU",
    },
    {
        min: 13568256,
        max: 13568512,
        name: "STU_ALT",
    },
    {
        min: 13762560,
        max: 13828096,
        name: "LDI",
    },
    {
        min: 14092288,
        max: 14092544,
        name: "LDI_ALT",
    },
    {
        min: 13828096,
        max: 13893632,
        name: "LDU",
    },
    {
        min: 14092544,
        max: 14092800,
        name: "LDU_ALT",
    },
    {
        min: 14024704,
        max: 14090240,
        name: "LDSLICE",
    },
    {
        min: 14097408,
        max: 14097664,
        name: "LDSLICE_ALT",
    },
    {
        min: 11272192,
        max: 11337728,
        name: "LSHIFT_VAR",
    },
    {
        min: 11141120,
        max: 11206656,
        name: "LSHIFT",
    },
    {
        min: 12037120,
        max: 12037376,
        name: "QLSHIFT_VAR",
    },
    {
        min: 12036608,
        max: 12036864,
        name: "QLSHIFT",
    },
    {
        min: 13580544,
        max: 13580800,
        name: "BCHKBITS_VAR",
    },
    {
        min: 13580288,
        max: 13580544,
        name: "BCHKBITS",
    },
    {
        min: 13581568,
        max: 13581824,
        name: "BCHKBITSQ_VAR",
    },
    {
        min: 13581312,
        max: 13581568,
        name: "BCHKBITSQ",
    },
    {
        min: 11337728,
        max: 11403264,
        name: "RSHIFT_VAR",
    },
    {
        min: 11206656,
        max: 11272192,
        name: "RSHIFT",
    },
    {
        min: 11084800,
        max: 11085056,
        name: "RSHIFT_ALT",
    },
    {
        min: 12037376,
        max: 12037632,
        name: "QRSHIFT_VAR",
    },
    {
        min: 12036864,
        max: 12037120,
        name: "QRSHIFT",
    },
    {
        min: 12036388,
        max: 12036389,
        name: "QRSHIFT_ALT",
    },
    {
        min: 15728640,
        max: 15794176,
        name: "CALLDICT",
    },
    {
        min: 15794176,
        max: 15810560,
        name: "CALLDICT_LONG",
    },
    {
        min: 15859712,
        max: 15876096,
        name: "THROW_SHORT",
    },
    {
        min: 15908864,
        max: 15910912,
        name: "THROW",
    },
    {
        min: 15876096,
        max: 15892480,
        name: "THROWIF_SHORT",
    },
    {
        min: 15912960,
        max: 15915008,
        name: "THROWIF",
    },
    {
        min: 15892480,
        max: 15908864,
        name: "THROWIFNOT_SHORT",
    },
    {
        min: 15917056,
        max: 15919104,
        name: "THROWIFNOT",
    },
    {
        min: 7340032,
        max: 8388608,
        name: "PUSHINT_4",
    },
    {
        min: 8388608,
        max: 8454144,
        name: "PUSHINT_8",
    },
    {
        min: 8454144,
        max: 8519680,
        name: "PUSHINT_16",
    },
    {
        min: 8519680,
        max: 8583168,
        name: "PUSHINT_LONG",
    },
    {
        min: 1114112,
        max: 1179648,
        name: "XCHG_0I_LONG",
    },
    {
        min: 131072,
        max: 1048576,
        name: "XCHG_0I",
    },
    {
        min: 1048576,
        max: 1114112,
        name: "XCHG_IJ",
    },
    {
        min: 1179648,
        max: 2097152,
        name: "XCHG_1I",
    },
    {
        min: 16646144,
        max: 16646400,
        name: "DUMPSTK",
    },
    {
        min: 16646400,
        max: 16651264,
        name: "DEBUG",
    },
    {
        min: 16651264,
        max: 16651520,
        name: "STRDUMP",
    },
    {
        min: 16651520,
        max: 16654336,
        name: "DEBUG_1",
    },
    {
        min: 16654336,
        max: 16658432,
        name: "DUMP",
    },
    {
        min: 16658432,
        max: 16707584,
        name: "DEBUG_2",
    },
    {
        min: 15548416,
        max: 15550464,
        name: "PUSHCTR",
    },
    {
        min: 2228224,
        max: 3145728,
        name: "PUSH",
    },
    {
        min: 5636096,
        max: 5701632,
        name: "PUSH_LONG",
    },
    {
        min: 15552512,
        max: 15554560,
        name: "POPCTR",
    },
    {
        min: 3276800,
        max: 4194304,
        name: "POP",
    },
    {
        min: 5701632,
        max: 5767168,
        name: "POP_LONG",
    },
    {
        min: 14352384,
        max: 14356480,
        name: "CALLXARGS",
    },
    {
        min: 14286848,
        max: 14352384,
        name: "CALLXARGS_1",
    },
    {
        min: 9109504,
        max: 9175040,
        name: "PUSHSLICE",
    },
    {
        min: 9175040,
        max: 9240576,
        name: "PUSHSLICE_REFS",
    },
    {
        min: 9240576,
        max: 9281536,
        name: "PUSHSLICE_LONG",
    },
    {
        min: 9306112,
        max: 9437184,
        name: "PUSHCONT",
    },
    {
        min: 9437184,
        max: 10485760,
        name: "PUSHCONT_SHORT",
    },
    {
        min: 13598720,
        max: 13631488,
        name: "STSLICECONST",
    },
    {
        min: 16711680,
        max: 16773120,
        name: "SETCP",
    },
    {
        min: 16773120,
        max: 16773376,
        name: "SETCPX",
    },
    {
        min: 16773376,
        max: 16777216,
        name: "SETCP_SHORT",
    },
    {
        min: 16340224,
        max: 16340480,
        name: "DEBUGMARK",
    },
]
