name: Security checks

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/security.yml
      - bunfig.toml
      - package.json
      - bun.lock
  push:
    branches:
      - master
    paths:
      - .github/workflows/security.yml
      - bunfig.toml
      - package.json
      - bun.lock
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: { }

jobs:
  security:
    name: Security checks
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Fetch Sources
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

      - name: Run Bun audit
        run: bun audit --audit-level=moderate
