name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  HUSKY: 0

jobs:
  tests:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Enable Corepack
        if: matrix.os == 'windows-latest'
        run: corepack enable --install-directory 'C:\npm\prefix'

      - name: Enable Corepack
        if: matrix.os != 'windows-latest'
        run: corepack enable

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "yarn"

      - name: Install dependencies
        env:
          YARN_ENABLE_HARDENED_MODE: false
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Run Tests
        run: yarn test
